[Feat] 게시글 생성 api 구현
BookitList/BookitList_backend pull request #47
Opened 2024-01-28 05:47 UTC by GGHDMS

## PR 변경된 내용
- 게시글 생성 api 구현
- 테스트 로직에 ` @WithCustomMockUser` 생성함

## 추가 내용
bookId 정보는 requestBody를 통새 받는다

## 참조
Closes #44

2024-01-28 09:06 UTC, morenow98 approved these changes

2024-01-28 09:06 UTC, morenow98 commented on src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
> +        String tooLongTitle = "Tooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
😁

2024-01-28 15:27 UTC, morenow98 requested changes

2024-01-28 15:27 UTC, morenow98 commented on src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
> +        mockMvc.perform(post("/books/100/posts")
이 부분 endpoint가 잘못돼서 테스트 통과되는 거 같은데?

2024-01-29 04:54 UTC, GGHDMS commented on src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
> +        mockMvc.perform(post("/books/100/posts")
오 굳굳!! 어떻게 찾았대?

2024-01-29 09:03 UTC, morenow98 approved these changes

2024-01-29 09:03 UTC, morenow98 commented on src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
> +        mockMvc.perform(post("/posts")
👍

2024-01-29 09:04 UTC, merged